"""empty message

Revision ID: 56477e80fb9f
Revises: a7b4758f56a4
Create Date: 2018-10-11 13:54:53.329665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56477e80fb9f'
down_revision = 'a7b4758f56a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('url', sa.Unicode(length=100), nullable=True))
    op.add_column('users', sa.Column('secret', sa.Unicode(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'secret')
    op.drop_column('playlists', 'url')
    # ### end Alembic commands ###
