"""empty message

Revision ID: 6e9dafca2de5
Revises: 56477e80fb9f
Create Date: 2018-10-13 14:52:38.601069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9dafca2de5'
down_revision = '56477e80fb9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('country', sa.Unicode(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'country')
    # ### end Alembic commands ###
