"""empty message

Revision ID: a7b4758f56a4
Revises: d4afc85f1a65
Create Date: 2018-10-05 16:41:28.773499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b4758f56a4'
down_revision = 'd4afc85f1a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('city', sa.Unicode(length=80), nullable=True))
    op.add_column('locations', sa.Column('state', sa.Unicode(length=2), nullable=True))
    op.add_column('playlist_users', sa.Column('playlist_id', sa.Integer(), nullable=True))
    op.add_column('playlist_users', sa.Column('status', sa.Unicode(length=1024), nullable=True))
    op.add_column('playlist_users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_playlist_users_playlist_id'), 'playlist_users', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_users_user_id'), 'playlist_users', ['user_id'], unique=False)
    op.create_foreign_key(None, 'playlist_users', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'playlist_users', 'playlists', ['playlist_id'], ['id'])
    op.add_column('playlists', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_playlists_location_id'), 'playlists', ['location_id'], unique=False)
    op.create_foreign_key(None, 'playlists', 'locations', ['location_id'], ['id'])
    op.add_column('users', sa.Column('first_name', sa.Unicode(length=1024), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.Unicode(length=1024), nullable=True))
    op.add_column('users', sa.Column('username', sa.Unicode(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_constraint(None, 'playlists', type_='foreignkey')
    op.drop_index(op.f('ix_playlists_location_id'), table_name='playlists')
    op.drop_column('playlists', 'location_id')
    op.drop_constraint(None, 'playlist_users', type_='foreignkey')
    op.drop_constraint(None, 'playlist_users', type_='foreignkey')
    op.drop_index(op.f('ix_playlist_users_user_id'), table_name='playlist_users')
    op.drop_index(op.f('ix_playlist_users_playlist_id'), table_name='playlist_users')
    op.drop_column('playlist_users', 'user_id')
    op.drop_column('playlist_users', 'status')
    op.drop_column('playlist_users', 'playlist_id')
    op.drop_column('locations', 'state')
    op.drop_column('locations', 'city')
    # ### end Alembic commands ###
